FROM node:18.20.2-slim
ENV TZ="Asia/Bangkok"
WORKDIR /app
COPY client/package.json client/package-lock.json .env.client ./
RUN npm install
COPY client .
RUN cp .env.client .env
# RUN (cd client && npm install)
EXPOSE 4000
CMD ["npm", "run", "dev"]