FROM node:18.20.2-slim
ENV TZ="Asia/Bangkok"
WORKDIR /server
COPY server/package.json server/package-lock.json .env.server ./
RUN npm install
COPY server .
#ENV ENV_FILE=.env.server
RUN cp .env.server .env
EXPOSE 4000
CMD ["npm", "run", "dev"]